remove function

diff --git a/todo b/todo
--- a/todo
+++ b/todo
@@ -18,7 +18,7 @@ fi
 
 if [[ $1 == 'list' ]]; then
   echo "# To be done"
-  cat "$TASK_FILE"
+  grep '^[0-9]' "$TASK_FILE"
   echo "# Completed"
   echo "Empty"
 fi
@@ -27,7 +27,10 @@ if [[ $1 == 'add' ]]; then
   shift
   declare -r TASK_TITLE="$*"
 
-  declare -r LAST_TASK_ID=$(cat "$TASK_FILE" | tail -n1 | cut -d' ' -f1)
+  declare LAST_TASK_ID
+  LAST_TASK_ID=$(tail -n1 "$TASK_FILE" | cut -d' ' -f1)
+  declare -r LAST_TASK_ID
+
   declare -r TASK_ID=$(( LAST_TASK_ID + 1 ))
   echo "$TASK_ID $TASK_TITLE" >>"$TASK_FILE"
 fi
@@ -37,5 +40,16 @@ if [[ $1 == 'edit' ]]; then
   shift 2
   declare -r TASK_TITLE="$*"
 
-  sed "s/^${TASK_ID} .*/${TASK_ID} ${TASK_TITLE}/" "$TASK_FILE"
+  if ! grep --silent "^${TASK_ID} " "$TASK_FILE"; then
+    echo "Task not found!"
+    exit 1
+  fi
+
+  sed -i '' "s/^${TASK_ID} .*/${TASK_ID} ${TASK_TITLE}/" "$TASK_FILE"
+fi
+
+if [[ $1 == 'remove' ]]; then
+  for TASK_ID in "$@"; do
+    sed -i '' "s/^${TASK_ID} /-&/" "$TASK_FILE"
+  done
 fi
